### ISSUE TITLE
Aliyun SDK有更新，麻烦升级一下谢谢。

### ISSUE THREAD

**Issue by alleniver** [yoonzm/react-native-ali-onepass#10]
这个组件很有用，解决了我应用登录的大问题，非常感谢。
SDK在1月20号有更新，
https://help.aliyun.com/document_detail/121113.html?spm=a2c4g.11186623.6.557.20977d501HlF54
麻烦更新一下，谢谢！

**Comment by alleniver** [comment]
还有我反馈个问题，目前好像有部分品牌的手机识别不出来，这个问题能修复吗？

**Comment by alleniver** [comment]
确认了下应该是没有打开蜂窝网络的手机无法识别到一键登录，这个问题不大。

**Comment by yoonzm** [comment]
@alleniver 有空更新
