### ISSUE TITLE
iOS和安卓无法拉起授权UI页面

### ISSUE THREAD

**Issue by liubi520** [yoonzm/react-native-ali-onepass#13]
提示授权页成功唤起后，页面无任何操作，并没有唤起授权页面

**Comment by benchenchuang** [comment]
> 提示授权页成功唤起后，页面无任何操作，并没有唤起授权页面

你的问题解决了嘛？

**Comment by yoonzm** [comment]
@liubi520 ，请问解决了吗，如果没有麻烦提供下复现的demo

**Comment by yoonzm** [comment]
先关掉了哈，有问题重新开issue
