### ISSUE TITLE
RNAliOnepass.podspec    配置有问题无法自动安装

### ISSUE THREAD

**Issue by hxzAugustinus** [yoonzm/react-native-ali-onepass#2]
RNAliOnepass.podspec 应该放在最外层，而不是ios 文件夹
homepage 字段不能为空
source_files  = "ios/**/*.{h,m}"
关键是  ATAuthSDK.framework 和 对应的bundle 的引入没搞懂

**Comment by hxzAugustinus** [comment]
@yoonzm    提了个requests ，看一下

**Comment by yoonzm** [comment]
@hxzAugustinus 目前是静态引入的framework，所以不需要pod install，此文件目前没用

**Comment by hxzAugustinus** [comment]
额，RNAliOnepass.m 和 RNAliOnepass.h 还是要使用cocospod 导入的，除非了所有的文件手动，不然我第一次使用时，是报错  包加载为null

**Comment by yoonzm** [comment]
@hxzAugustinus 
1.ios自动link后是直接可以正常使用的，不太清楚你那边是遇到什么样的问题
2.安卓这边aar文件确实需要在app/build.gradle添加下面的代码
```
    repositories {
        flatDir {
            dirs 'libs', '../../node_modules/react-native-ali-onepass/android/libs'
        }
    }
```

**Comment by hxzAugustinus** [comment]
我iOS的执行顺序 ：1.  npm  i react-native-ali-onepass --save
2. react-native link react-native-ali-onepass
3. cd  ios  &&  pod  install  ，然后就执行编译就报有个module 找不到

**Comment by hxzAugustinus** [comment]
我下午给你提供一个pod 截图  和  运行编译截图吧

**Comment by yoonzm** [comment]
@hxzAugustinus 不需要执行你的第三步，因为不需要导入动态库

**Comment by hxzAugustinus** [comment]
老哥，你这样，我后面添加其他的东西，也要执行d ios && pod install 呀

**Comment by yoonzm** [comment]
@hxzAugustinus .podspec文件是创建项目时生成的，因为没有使用到所以没有去修改

**Comment by yoonzm** [comment]
@hxzAugustinus 是因为你把此项目的pod添加到你的项目的podfile了吧

**Comment by hxzAugustinus** [comment]
嗯，是的

**Comment by yoonzm** [comment]
@hxzAugustinus 明白了，我看下

**Comment by hxzAugustinus** [comment]
好的，还是推荐修改 .podspec使用autolinKing,  多谢回复

**Comment by yoonzm** [comment]
好的

**Comment by yoonzm** [comment]
@hxzAugustinus 请问一下你们项目的rn版本是多少，我们一直使用的0.48.4版本的，我试了下是正常的

**Comment by hxzAugustinus** [comment]
我的是0.61.5

**Comment by hxzAugustinus** [comment]
@yoonzm    发布的有点问题  这个 RNAliOnepass.podspec 没包含

**Comment by yoonzm** [comment]
@hxzAugustinus 没明白你说的，方便的话你加我QQ吧: yzm782151712
