### ISSUE TITLE
logBtnBackgroundPaths属性会报错

### ISSUE THREAD

**Issue by TroubleSeven** [yoonzm/react-native-ali-onepass#20]
![image](https://user-images.githubusercontent.com/24597508/121457402-325de580-c9da-11eb-9b51-2b13d2369faa.png)
注释以后可以正常运行。
另外有兄弟知道图片的路径怎么替换吗

**Comment by yoonzm** [comment]
@TroubleSeven https://github.com/yoonzm/react-native-ali-onepass/tree/master/example/ios/onepass/Images.xcassets
看一下这个路径下的文件

**Comment by TroubleSeven** [comment]
@yoonzm 感谢老哥，这个没问题了。请问一下 其它方式登陆 这个地方咋用的，怎么样放icon进去跳链呢

**Comment by yoonzm** [comment]
https://github.com/yoonzm/react-native-ali-onepass/blob/79aa323143e09244334a77f1a85e761615be4ef2/index.js#L103
https://github.com/yoonzm/react-native-ali-onepass/blob/79aa323143e09244334a77f1a85e761615be4ef2/example/App.js#L35
@TroubleSeven 
监听事件里面有这个类型

**Comment by TroubleSeven** [comment]
谢谢老哥，新的问题 logoWidth /  logoHeight 这两个属性 IOS里自定义大小失效 @yoonzm

**Comment by TroubleSeven** [comment]
照葫芦画瓢提了一个issues 修复了上面那个问题，再问下老哥页面背景颜色怎么修改呢，是否可以增加一个设置背景图片的api暴露出来 🙏

**Comment by yoonzm** [comment]
@TroubleSeven 这个我得看下能不能设置
