### ISSUE TITLE
ios 运行Simulator报错ATAuthSDK.framework/ATAuthSDK' for architecture arm64

### ISSUE THREAD

**Issue by basilbai** [yoonzm/react-native-ali-onepass#29]
版本信息
`
"react-native": "0.66.4",
"react-native-ali-onepass": "^2.1.0",
`
运行真机正常，在iOS 模拟器上报错
`
in /Users/mac/deafaidPro/node_modules/react-native-ali-onepass/ios/libs/ATAuthSDK.framework/ATAuthSDK(TXSecurityUtils.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/mac/deafaidPro/node_modules/react-native-ali-onepass/ios/libs/ATAuthSDK.framework/ATAuthSDK' for architecture arm64
`
请问怎么解决？

**Comment by yoonzm** [comment]
@basilbai 这是运营商的服务，不支持模拟器，请使用真机调试

**Comment by basilbai** [comment]
@yoonzm 好的,感谢🙏
