### ISSUE TITLE
RN 0.67.2版本，安卓打包报错

### ISSUE THREAD

**Issue by Pilotager** [yoonzm/react-native-ali-onepass#31]
大佬，安卓打包报错~，这个有什么办法可以解决嘛

> Task :react-native-ali-onepass:verifyReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-ali-onepass:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/Users/yinhang/.gradle/caches/transforms-3/8bb9561c589f5cd8f762c133b8ca94b9/transformed/appcompat-1.0.2/res/values-v26/values-v26.xml:5:5-8:13: AAPT: error: resource android:attr/colorError not found.

     ERROR:/Users/yinhang/.gradle/caches/transforms-3/8bb9561c589f5cd8f762c133b8ca94b9/transformed/appcompat-1.0.2/res/values-v26/values-v26.xml:9:5-12:13: AAPT: error: resource android:attr/colorError not found.

     ERROR:/Users/yinhang/.gradle/caches/transforms-3/8bb9561c589f5cd8f762c133b8ca94b9/transformed/appcompat-1.0.2/res/values-v26/values-v26.xml:13:5-16:13: AAPT: error: style attribute 'android:attr/keyboardNavigationCluster' not found.

     ERROR:/Users/yinhang/.gradle/caches/transforms-3/8bb9561c589f5cd8f762c133b8ca94b9/transformed/appcompat-1.0.2/res/values-v28/values-v28.xml:5:5-8:13: AAPT: error: resource android:attr/dialogCornerRadius not found.

     ERROR:/Users/yinhang/.gradle/caches/transforms-3/8bb9561c589f5cd8f762c133b8ca94b9/transformed/appcompat-1.0.2/res/values-v28/values-v28.xml:9:5-12:13: AAPT: error: resource android:attr/dialogCornerRadius not found.

     ERROR:/Users/yinhang/.gradle/caches/transforms-3/2780a7d58323a095a84203f45c645c6e/transformed/core-1.1.0/res/values/values.xml:142:5-173:25: AAPT: error: resource android:attr/fontStyle not found.

     ERROR:/Users/yinhang/.gradle/caches/transforms-3/2780a7d58323a095a84203f45c645c6e/transformed/core-1.1.0/res/values/values.xml:142:5-173:25: AAPT: error: resource android:attr/font not found.

     ERROR:/Users/yinhang/.gradle/caches/transforms-3/2780a7d58323a095a84203f45c645c6e/transformed/core-1.1.0/res/values/values.xml:142:5-173:25: AAPT: error: resource android:attr/fontWeight not found.

     ERROR:/Users/yinhang/.gradle/caches/transforms-3/2780a7d58323a095a84203f45c645c6e/transformed/core-1.1.0/res/values/values.xml:142:5-173:25: AAPT: error: resource android:attr/fontVariationSettings not found.

     ERROR:/Users/yinhang/.gradle/caches/transforms-3/2780a7d58323a095a84203f45c645c6e/transformed/core-1.1.0/res/values/values.xml:142:5-173:25: AAPT: error: resource android:attr/ttcIndex not found.

     ERROR:/Users/yinhang/.gradle/caches/transforms-3/2780a7d58323a095a84203f45c645c6e/transformed/core-1.1.0/res/values/values.xml:174:5-210:25: AAPT: error: resource android:attr/startX not found.

**Comment by yoonzm** [comment]
https://blog.csdn.net/ggb147258369/article/details/103231528
