### ISSUE TITLE
 新版本ios 打包 报错不支持 bitcode

### ISSUE THREAD

**Issue by mzyisbest** [yoonzm/react-native-ali-onepass#37]
Showing All Messages
Bitcode bundle could not be generated because '/Users/mazhaoyang/yysapp/node_modules/react-native-ali-onepass/ios/libs/ATAuthSDK.framework/ATAuthSDK(ATAuthSDK99999999.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build file '/Users/mazhaoyang/yysapp/node_modules/react-native-ali-onepass/ios/libs/ATAuthSDK.framework/ATAuthSDK' for architecture arm64

通过关闭bitcode  可以解决    但还是想问下能不能改成可以支持bitcode的  毕竟关闭bitcode后 包体积增加了7M  不友好

**Comment by yoonzm** [comment]
当前库只是将原生sdk整合为支持rn跨平台调用，具体原生sdk是否支持bitcode是阿里云那边控制的，可以联系他们问一下
