### ISSUE TITLE
安卓编译异常了

### ISSUE THREAD

**Issue by zhengzhiwu2009** [yoonzm/react-native-ali-onepass#38]
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find :auth_number_product-2.12.4-SNAPSHOT-log-online-standard-release:.
     Required by:
         project :app > project :react-native-ali-onepass
   > Could not find :crashshield-2.1.4-release:.
     Required by:
         project :app > project :react-native-ali-onepass
   > Could not find :main-2.1.4-release:.
     Required by:
         project :app > project :react-native-ali-onepass
   > Could not find :logger-2.1.4-release:.
     Required by:
         project :app > project :react-native-ali-onepass

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s

    at makeError (D:\area-edu-app\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:174:9)
    at D:\area-edu-app\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (D:\area-edu-app\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (D:\area-edu-app\node_modules\@react-native-community\cli\build\index.js:192:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by yoonzm** [comment]
repositories {
      flatDir {
          dirs 'libs', '../../node_modules/react-native-ali-onepass/android/libs'
      }
  }
