### ISSUE TITLE
oppo 手机 一键登录 大概率失败

### ISSUE THREAD

**Issue by hxzAugustinus** [yoonzm/react-native-ali-onepass#4]
Unable to start activity ComponentInfo{com.xxxxx/com.cmic.sso.sdk.activity.LoginAuthActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Looper android.content.Context.getMainLooper()' on a null object reference

**Comment by yoonzm** [comment]
[demo](https://www.pgyer.com/zupE)
你下载这个demo试下能否复现，我在oppo手机上试了下没有出现问题。
或者你这边看方便提供一个可以复现的demo吗？
