### ISSUE TITLE
找不到 libRNAliOnepass.a

### ISSUE THREAD

**Issue by silverbulllet** [yoonzm/react-native-ali-onepass#42]
找不到 **libRNAliOnepass.a**  这个文件，该怎么办呢？

![image](https://user-images.githubusercontent.com/6985218/211259560-d36cbb5b-97b9-45f5-9556-a9cfd3e7ae83.png)

**Comment by jswangtao** [comment]
> 找不到 **libRNAliOnepass.a** 这个文件，该怎么办呢？
> 
> ![image](https://user-images.githubusercontent.com/6985218/211259560-d36cbb5b-97b9-45f5-9556-a9cfd3e7ae83.png)
请问你解决了吗，我也遇到相同的问题了

**Comment by yoonzm** [comment]
@silverbulllet @jswangtao 把rn版本贴一下

**Comment by yoonzm** [comment]
@silverbulllet @jswangtao 或者吧[example](https://github.com/yoonzm/react-native-ali-onepass/tree/master/example)跑一下对比下哪里不一样

**Comment by surethink** [comment]
@jswangtao @silverbulllet 两位后来这个问题怎么解决了，谢谢

**Comment by Liu-P** [comment]
@surethink @jswangtao @jswangtao 大佬们有解决这个问题，也碰到了这个问题

**Comment by yunianzhuang** [comment]
> @surethink @jswangtao @jswangtao大佬们解决了这个问题，也解决了这个问题



> @surethink @jswangtao @jswangtao大佬们解决了这个问题，也解决了这个问题

如果解决的朋友，求教
