### ISSUE TITLE
 找不到 **libRNAliOnepass.a** 这个文件

### ISSUE THREAD

**Issue by surethink** [yoonzm/react-native-ali-onepass#44]
按照instructions操作的，derived data清过，pod install 也做了
同样的问题;rn版本0.71.3

用xcode build后完整的报错：
clang: error: no such file or directory: '/Users/xxx/Library/Developer/Xcode/DerivedData/xxx-euhunlbhmsglbggqqaaiaqdsetcf/Build/Intermediates.noindex/ArchiveIntermediates/xxxx/BuildProductsPath/Release-iphoneos/libRNAliOnepass.a'
Command Ld failed with a nonzero exit code

麻烦看下，谢谢！

> 
> ![image](https://user-images.githubusercontent.com/6985218/211259560-d36cbb5b-97b9-45f5-9556-a9cfd3e7ae83.png)
请问你解决了吗，我也遇到相同的问题了

_Originally posted by @jswangtao in https://github.com/yoonzm/react-native-ali-onepass/issues/42#issuecomment-1413060557_

**Comment by surethink** [comment]
@yoonzm 麻烦给点建议？谢谢

**Comment by yoonzm** [comment]
@surethink 把[example](https://github.com/yoonzm/react-native-ali-onepass/tree/master/example)跑起来看一下对比下哪里不一样

**Comment by NgeKaworu** [comment]
遇到同样问题

**Comment by yunianzhuang** [comment]
> @yoonzm 麻烦给点建议？谢谢

朋友，你有解决吗，我rn的版本是合你一样的。。。。

**Comment by zhiminduan** [comment]
我解决了:
In XCode, in the project navigator, select your project. Add libRNAliOnepass.a to your project's Build Phases ➜ Link Binary With Libraries
 这个步骤选择 libRNAliOnepass.a  的时候，选择pod 中的文件，下图中红色箭头标识的：
<img width="328" alt="企业微信截图_7051c6c5-17c1-4217-9bf7-4bc5b54eaf9d" src="https://github.com/yoonzm/react-native-ali-onepass/assets/17423120/a38df655-7551-4baf-88ec-df1df6b61c7a">
