### ISSUE TITLE
可以更新下SDK吗  

### ISSUE THREAD

**Issue by mzyisbest** [yoonzm/react-native-ali-onepass#45]
IOS时不时报错600004  获取运营商配置信息失败。 官方建议  ：建议升级SDK版本。您可在号码认证服务控制台下载最新版SDK。

**Comment by mzyisbest** [comment]
https://help.aliyun.com/document_detail/2326795.html?spm=a2c4g.200275.0.0.de0b64f9soPXhI
ios16.4以后  废弃了CTCarrier功能导致的    等他们解决完再更新才能解决问题~

**Comment by yoonzm** [comment]
[](url)

> https://help.aliyun.com/document_detail/2326795.html?spm=a2c4g.200275.0.0.de0b64f9soPXhI ios16.4以后 废弃了CTCarrier功能导致的 等他们解决完再更新才能解决问题~

等官网解决后再更新吧

**Comment by mzyisbest** [comment]
@yoonzm 可以更新了  老哥 你去官网看下

**Comment by mzyisbest** [comment]
需要将号码认证SDK版本更新到 v2.12.14或以上版本

**Comment by yoonzm** [comment]
@mzyisbest 好的，我们近期更新下，如果着急环境提交pr

**Comment by mzyisbest** [comment]
我今天升级了一下，然后有个问题就是 在页面弹起的时候   
if([resultCode isEqualToString:PNSCodeSuccess]
        ||[resultCode isEqualToString:PNSCodeLoginControllerPresentSuccess]
           || [resultCode isEqualToString:PNSCodeLoginControllerClickLoginBtn]
           || [resultCode isEqualToString:PNSCodeLoginControllerClickCheckBoxBtn]
           || [resultCode isEqualToString:PNSCodeLoginControllerClickProtocol]
           ) 
这里是数据类型没对上 之前作者用的 == 比对（SDK中的这个比对常量可能改成number类型了）  导致走了false   我用isEqualToString就可以了

**Comment by yoonzm** [comment]
> 我今天升级了一下，然后有个问题就是 在页面弹起的时候 if([resultCode isEqualToString:PNSCodeSuccess] ||[resultCode isEqualToString:PNSCodeLoginControllerPresentSuccess] || [resultCode isEqualToString:PNSCodeLoginControllerClickLoginBtn] || [resultCode isEqualToString:PNSCodeLoginControllerClickCheckBoxBtn] || [resultCode isEqualToString:PNSCodeLoginControllerClickProtocol] ) 这里是数据类型没对上 之前作者用的 == 比对（SDK中的这个比对常量可能改成number类型了） 导致走了false 我用isEqualToString就可以了

厉害呀，没问题的话提个pr发一版试试

**Comment by mzyisbest** [comment]
@yoonzm 提交了。你看看能合吗  我自测的目前没问题

**Comment by yoonzm** [comment]
> @yoonzm 提交了。你看看能合吗 我自测的目前没问题
@mzyisbest 好的，合并了，正在自动发版，感谢

**Comment by mzyisbest** [comment]
@yoonzm OK~
