### ISSUE TITLE
react-native 0.62版本打包时报错

### ISSUE THREAD

**Issue by ding991** [yoonzm/react-native-ali-onepass#5]
react-native 0.62版本打包时报错，错误如下图
<img width="1235" alt="C2BD3203-2D11-4E15-9314-5E4279BC3489" src="https://user-images.githubusercontent.com/42601540/88374548-7baa4400-cdcc-11ea-9174-5abd18e9b824.png">

**Comment by tanjiaweiGitHub** [comment]
@ding991      import android.support.annotation.Nullable;   =>   import androidx.annotation.Nullable;

**Comment by ding991** [comment]
@tanjiaweiGitHub  这个错误解决了，然后又报了个错误
<img width="1214" alt="790AB0D6-4E55-48A2-96D9-A103B8316E17" src="https://user-images.githubusercontent.com/42601540/88382483-2590cd00-cddb-11ea-8768-5fae3db06d37.png">

**Comment by tanjiaweiGitHub** [comment]
@ding991  试试     cd android && ./gradlew clean && cd ..

**Comment by ding991** [comment]
@tanjiaweiGitHub 谢谢了，但是清缓存也没用，还是有这个问题。

**Comment by yoonzm** [comment]
@ding991 @tanjiaweiGitHub 为了兼容，已删掉Nullable注解，谢谢
