### ISSUE TITLE
有考虑接最新的sdk吗？ios 是v2.13.2-2024.01.03，android :v2.13.2

### ISSUE THREAD

**Issue by CharonTao** [yoonzm/react-native-ali-onepass#56]
按照阿里云最新的sdk版本通知，目前项目的版本，在联通卡上面已经无法使用，会提示 "102，应用无效 "。这个时候需要升级sdk,而且这个升级是大版本升级，和旧的不兼容，不知道作者大大是否有意愿同步升级一下哈

**Comment by yoonzm** [comment]
@CharonTao 我们已收到阿里的升级通知了，近期会更新至最新版本

**Comment by CharonTao** [comment]
好的，非常感谢！！！

**Comment by kanglang** [comment]
期待早日升级，3月份以后旧的sdk就不能使用了

**Comment by DarrenJobs** [comment]
![image](https://github.com/yoonzm/react-native-ali-onepass/assets/29941848/6479c204-095f-49c8-814a-095a313b94f0)
期待作者早日更新，感谢

**Comment by 86chenjie** [comment]
请问 这个什么时候能完成？刚好需要这个。谢谢！

**Comment by yoonzm** [comment]
已升级
react-native-ali-onepass@3.4.0
