### ISSUE TITLE
ios 背景色无法定制

### ISSUE THREAD

**Issue by clycheng2015** [yoonzm/react-native-ali-onepass#9]
你好，iOS上，授权页的背景色是不是没办法进行定制啊？目前接完后背景是白色的，是应用中哪里没设置好还是SDK本身没暴露出接口？我在阿里官方iOS文档也没看到对应的api可以设置背景图或者背景色？请问，你们是怎么理解的？有什么办法可以修改这个背景吗？谢谢！
react-native:0.61.5

**Comment by yoonzm** [comment]
目前sdk是没有提供修改页面背景的功能
